site_title = "Arxiv channel"
limit_days = 7
cache_url = "https://wzetto.github.io/MyArxiv/cache.json"

[[sources]]
limit = 25
category = "cond-mat.dis-nn"
title = "Disordered Systems and Neural Networks"

[[sources]]
limit = 25
category = "cond-mat.mtrl-sci"
title = "Materials Science"

[[sources]]
limit = 25
category = "physics.data-an"
title = "Data Analysis, Statistics and Probability"

[[sources]]
limit = 25
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 25
category = "q-fin.CP"
title = "Computational Finance"

[[sources]]
limit = 25
category = "cs.LG"
title = "Machine Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
